INSERT IGNORE INTO Hotel (name, city) VALUES
('Hotel Royal', 'Paris'),
('Ocean Breeze Resort', 'Nice'),
('Mountain Lodge', 'Toulouse'),
('City Lights Hotel', 'Lyon'),
('Lakeside Inn', 'Marseille');

ALTER TABLE Room ADD UNIQUE (hotel_id, room_number);
INSERT IGNORE INTO Room (hotel_id, room_type, room_number, view, bed_type, accessibility, price_per_night, description) VALUES
(1, 'double', '101', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(1, 'single', '102', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(1, 'suite', '103', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(1, 'double', '104', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(1, 'single', '105', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(1, 'double', '106', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(1, 'suite', '107', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(1, 'single', '108', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(1, 'double', '109', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(1, 'single', '110', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(1, 'double', '111', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(1, 'single', '112', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(1, 'suite', '113', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(1, 'double', '114', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(1, 'single', '115', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(1, 'double', '116', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(1, 'suite', '117', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(1, 'single', '118', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(1, 'double', '119', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(1, 'single', '120', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(1, 'double', '121', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(1, 'single', '122', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(1, 'suite', '123', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(1, 'double', '124', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(1, 'single', '125', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(1, 'double', '126', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(1, 'suite', '127', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(1, 'single', '128', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(1, 'double', '129', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),

(2, 'double', '101', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(2, 'single', '102', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(2, 'suite', '103', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(2, 'double', '104', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(2, 'single', '105', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(2, 'double', '106', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(2, 'suite', '107', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(2, 'single', '108', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(2, 'double', '109', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(2, 'single', '110', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(2, 'double', '111', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(2, 'single', '112', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(2, 'suite', '113', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(2, 'double', '114', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(2, 'single', '115', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(2, 'double', '116', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(2, 'suite', '117', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(2, 'single', '118', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(2, 'double', '119', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(2, 'single', '120', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(2, 'double', '121', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(2, 'single', '122', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(2, 'suite', '123', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(2, 'double', '124', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(2, 'single', '125', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(2, 'double', '126', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(2, 'suite', '127', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(2, 'single', '128', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(2, 'double', '129', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),

(3, 'double', '101', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(3, 'single', '102', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(3, 'suite', '103', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(3, 'double', '104', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(3, 'single', '105', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(3, 'double', '106', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(3, 'suite', '107', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(3, 'single', '108', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(3, 'double', '109', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(3, 'single', '110', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(3, 'double', '111', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(3, 'single', '112', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(3, 'suite', '113', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(3, 'double', '114', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(3, 'single', '115', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(3, 'double', '116', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(3, 'suite', '117', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(3, 'single', '118', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(3, 'double', '119', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(3, 'single', '120', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(3, 'double', '121', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(3, 'single', '122', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(3, 'suite', '123', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(3, 'double', '124', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(3, 'single', '125', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(3, 'double', '126', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(3, 'suite', '127', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(3, 'single', '128', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(3, 'double', '129', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),

(4, 'double', '101', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(4, 'single', '102', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(4, 'suite', '103', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(4, 'double', '104', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(4, 'single', '105', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(4, 'double', '106', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(4, 'suite', '107', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(4, 'single', '108', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(4, 'double', '109', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(4, 'single', '110', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(4, 'double', '111', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(4, 'single', '112', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(4, 'suite', '113', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(4, 'double', '114', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(4, 'single', '115', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(4, 'double', '116', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(4, 'suite', '117', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(4, 'single', '118', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(4, 'double', '119', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(4, 'single', '120', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(4, 'double', '121', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(4, 'single', '122', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(4, 'suite', '123', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(4, 'double', '124', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(4, 'single', '125', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(4, 'double', '126', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(4, 'suite', '127', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(4, 'single', '128', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(4, 'double', '129', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),

(5, 'double', '101', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(5, 'single', '102', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(5, 'suite', '103', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(5, 'double', '104', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(5, 'single', '105', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(5, 'double', '106', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(5, 'suite', '107', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(5, 'single', '108', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(5, 'double', '109', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(5, 'single', '110', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(5, 'double', '111', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(5, 'single', '112', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(5, 'suite', '113', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(5, 'double', '114', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(5, 'single', '115', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(5, 'double', '116', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(5, 'suite', '117', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(5, 'single', '118', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(5, 'double', '119', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view'),
(5, 'single', '120', 'city', 'Queen', 'No', 125.00, 'Compact standard room with modern decor'),
(5, 'double', '121', 'city', 'King', 'Yes', 150.00, 'Spacious deluxe room with city view'),
(5, 'single', '122', 'garden', 'Queen', 'No', 120.00, 'Comfortable standard room with garden view'),
(5, 'suite', '123', 'city', 'King', 'Yes', 250.00, 'Luxurious suite with panoramic city view'),
(5, 'double', '124', 'sea', 'King', 'Yes', 180.00, 'Elegant deluxe room with river view'),
(5, 'single', '125', 'city', 'Twin', 'No', 110.00, 'Cozy standard room with city view'),
(5, 'double', '126', 'city', 'King', 'Yes', 160.00, 'Modern deluxe room with city skyline view'),
(5, 'suite', '127', 'garden', 'King', 'Yes', 270.00, 'Luxury suite with garden and balcony'),
(5, 'single', '128', 'city', 'Twin', 'No', 115.00, 'Quiet standard room with city street view'),
(5, 'double', '129', 'sea', 'King', 'Yes', 190.00, 'Deluxe room with direct riverfront view');